services:
  live-query:
    container_name: live-query
    build: .
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8002
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - chroma-db

  chroma-db:
    container_name: chroma-db
    image: chromadb/chroma
    ports:
      - "8000:8000"